Models/Cmcustomer.cs
using System;
using System.Collections.Generic;

namespace Case.Web.Portal.Models
{
    public partial class Cmcustomer
    {
        public Cmcustomer()
        {
            Cmcases = new HashSet<Cmcase>();
        }

        public int Id { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string Email { get; set; } = null!;
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? PhoneNumber { get; set; }

        public virtual ICollection<Cmcase> Cmcases { get; set; }
    }
}

Controllers/CmcasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Case.Web.Portal.Models;

namespace Case.Web.Portal.Controllers
{
    public class CmcasesController : Controller
    {
        private readonly casemanagementContext _context;

        public CmcasesController(casemanagementContext context)
        {
            _context = context;
        }

        // GET: Cmcases
        public async Task<IActionResult> Index()
        {
            var casemanagementContext = _context.Cmcases.Include(c => c.CMcaseType).Include(c => c.CMcustomer).Include(c => c.CustomerCare);
            return View(await casemanagementContext.ToListAsync());
        }

        // GET: Cmcases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cmcases == null)
            {
                return NotFound();
            }

            var cmcase = await _context.Cmcases
                .Include(c => c.CMcaseType)
                .Include(c => c.CMcustomer)
                .Include(c => c.CustomerCare)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cmcase == null)
            {
                return NotFound();
            }

            return View(cmcase);
        }

        // GET: Cmcases/Create
        public IActionResult Create(int userId)
        {
            ViewData["CMcaseTypeId"] = new SelectList(_context.CmcaseTypes, "Id", "Name");
            ViewData["CMcaseType"] = new SelectList(_context.CmcaseTypes, "Id", "Name");
            ViewData["CMcustomerId"] = new SelectList(_context.Cmcustomers, "Id", "Email");
            ViewData["CustomerCareId"] = new SelectList(_context.CmcustomerCares, "Id", "Email");
            ViewData["CustomerId"] = userId;

            return View();
        }

        // POST: Cmcases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.


        [HttpPost]
        public JsonResult AutoComplete(string prefix)
        {
            var customers = (from customer in _context.Cmcustomers
                             where customer.FirstName!.StartsWith(prefix)
                             select new
                             {
                                 label = customer.Email,
                                 val = customer.Id
                             }).ToList();

            return Json(customers);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromQuery] int userId,[Bind("Id,Description,CustomerEmail,CaseTypeId,CustomerId")] CreateCase cmcase )
        {
            if (ModelState.IsValid)
            {
                var c = new Cmcase();
                var cs = _context.Cmcustomers.Where(c => c.Id == cmcase!.CustomerId).FirstOrDefault();
                var t = _context.CmcaseTypes.Where(c => c.Id == cmcase.CaseTypeId).FirstOrDefault();
                c.CMcustomer = cs!;
                c.Status = "Submitted";
                c.State = 0;
                c.CMcaseType = t;
                c.CMcaseTypeId = cmcase.CaseTypeId;
                c.Description = cmcase.Description;
                c.CustomerCare = _context.CmcustomerCares.Where(c=>c.Id == 1).FirstOrDefault();
                c.CreatedAt = DateTime.Now;
                c.ResolvedAt = DateTime.Now;
                _context.Add(c);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["CMcaseTypeId"] = new SelectList(_context.CmcaseTypes, "Id", "Name", cmcase.CMcaseTypeId);
            ViewData["CMcustomerId"] = new SelectList(_context.Cmcustomers, "Id", "Email", cmcase.CMcustomer);
            //ViewData["CustomerCareId"] = new SelectList(_context.CmcustomerCares, "Id", "Email", cmcase.CustomerCare);
            return View(cmcase);
        }

        // GET: Cmcases/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cmcases == null)
            {
                return NotFound();
            }

            var cmcase = await _context.Cmcases.FindAsync(id);
            var caseType = await _context.CmcaseTypes.FindAsync(cmcase.CMcaseTypeId);
            //var caseType = await _context.CmcaseTypes.FindAsync(cmcase.CaseTypeId);
            var c = new CreateCase();
            if (cmcase == null)
            {
                return NotFound();
            }
            if (cmcase.CustomerCare == null)
            {
                c.CustomerCare = null;
                c.CustomerCareEmail = "";
            }
            else{
                c.CustomerCare = await _context.CmcustomerCares.FindAsync(cmcase.CustomerCare!.Id);
                c.CustomerCareEmail = c.CustomerCare!.Email;
            }
            
            c.Id = cmcase.Id;
            c.CMcustomer = await _context.Cmcustomers.FindAsync(cmcase.Id);
            c.Status = cmcase.Status;
            c.ResolvedAt = cmcase.ResolvedAt;
           // c.CustomerCare= == null ? null : await _context.CmcustomerCares.FindAsync(cmcase.CustomerCare!.Id);
            c.Description = cmcase.Description;
            c.CaseTypeId = cmcase.CMcaseTypeId;
            //c.CaseTypeId = cmcase.CaseTypeId;

            c.CustomerEmail = c.CMcustomer!.Email;
            c.CaseTypeName = caseType.Name;
            

            ViewData["CMcaseTypeId"] = new SelectList(_context.CmcaseTypes, "Id", "Name", cmcase.CMcaseTypeId);
            ViewData["CaseTypeName"] = new SelectList(_context.Cmcustomers, "Id", "Email", cmcase.CMcaseType.Name);
            ViewData["CustomerCareId"] = new SelectList(_context.CmcustomerCares, "Id", "Email", cmcase.CustomerCare);
            return View(c);
        }

        // POST: Cmcases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,CustomerEmail,CaseTypeId,Status")] CreateCase cmcase)
        {


            if (id != cmcase.Id)
            {
                return NotFound();
            }



            var c = await _context.Cmcases.FindAsync(id);

            if (ModelState.IsValid)
            {
                try
                {
                   // var c = new Cmcase();
                    var cs = _context.Cmcustomers.Where(c => c.Email == cmcase.CustomerEmail).FirstOrDefault();
                    var t = _context.CmcaseTypes.Where(c => c.Id == cmcase.CaseTypeId).FirstOrDefault();
                    c!.CMcustomer = cs!;
                    c.Status = cmcase.Status!;
                    c.State = 0;
                    c.CMcaseType = t!;
                    c.CMcaseTypeId = cmcase.CaseTypeId;
                    c.CaseTypeId = cmcase.CaseTypeId;
                    c.Description = cmcase.Description;
                   // c.

                    if (c.CustomerCare == null)
                    {
                        c.CustomerCare = null;
                        //c.cm = "";
                    }
                    else
                    {
                        c.CustomerCare = await _context.CmcustomerCares.FindAsync(cmcase.CustomerCare!.Id);
                       // c.CustomerCareEmail = c.CustomerCare!.Email;
                    }

                   // c.CustomerCare = _context.CmcustomerCares.Where(c => c.Id == cmcase.CustomerCare!.Id).FirstOrDefault()!.Id != 1 ? _context.CmcustomerCares.Where(c => c.Id == cmcase.CustomerCare!.Id).FirstOrDefault() : _context.CmcustomerCares.Where(c => c.Id == 1).FirstOrDefault();
                   // c.CreatedAt = DateTime.Now;
                    c.ResolvedAt = DateTime.Now;
                    _context.Update(c);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CmcaseExists(cmcase.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CMcaseTypeId"] = new SelectList(_context.CmcaseTypes, "Id", "Name", c!.CMcaseTypeId);
            ViewData["CMcustomerId"] = new SelectList(_context.Cmcustomers, "Id", "Email", c.CMcustomer);
            ViewData["CustomerCareId"] = new SelectList(_context.CmcustomerCares, "Id", "Email", c.CustomerCare);
            return View(cmcase);
        }

        // GET: Cmcases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cmcases == null)
            {
                return NotFound();
            }

            var cmcase = await _context.Cmcases
                .Include(c => c.CMcaseType)
                .Include(c => c.CMcustomer)
                .Include(c => c.CustomerCare)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cmcase == null)
            {
                return NotFound();
            }

            return View(cmcase);
        }


        public async Task<IActionResult> Assign(int? id)
        {
            if (id == null || _context.Cmcases == null)
            {
                return NotFound();
            }

            //var cm = await _context.Cmcases
            //    .Include(c => c.CMcaseType)
            //    .Include(c => c.CMcustomer)
            //    .Include(c => c.CustomerCare)

Controllers/CmcustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Case.Web.Portal.Models;

namespace Case.Web.Portal.Controllers
{
    public class CmcustomersController : Controller
    {
        private readonly casemanagementContext _context;

        public CmcustomersController(casemanagementContext context)
        {
            _context = context;
        }

        // GET: Cmcustomers
        public async Task<IActionResult> Index()
        {
              return View(await _context.Cmcustomers.ToListAsync());
        }

        // GET: Cmcustomers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cmcustomers == null)
            {
                return NotFound();
            }

            var cmcustomer = await _context.Cmcustomers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cmcustomer == null)
            {
                return NotFound();
            }

            return View(cmcustomer);
        }

        // GET: Cmcustomers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cmcustomers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,CreatedAt,UpdatedAt,PhoneNumber")] Cmcustomer cmcustomer)
        {
            if (ModelState.IsValid)
            {
               
                _context.Add(cmcustomer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cmcustomer);
        }

        // GET: Cmcustomers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cmcustomers == null)
            {
                return NotFound();
            }

            var cmcustomer = await _context.Cmcustomers.FindAsync(id);
            if (cmcustomer == null)
            {
                return NotFound();
            }
            return View(cmcustomer);
        }

        // POST: Cmcustomers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,CreatedAt,UpdatedAt,PhoneNumber")] Cmcustomer cmcustomer)
        {
            if (id != cmcustomer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cmcustomer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CmcustomerExists(cmcustomer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cmcustomer);
        }

        // GET: Cmcustomers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cmcustomers == null)
            {
                return NotFound();
            }

            var cmcustomer = await _context.Cmcustomers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cmcustomer == null)
            {
                return NotFound();
            }

            return View(cmcustomer);
        }

        // POST: Cmcustomers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cmcustomers == null)
            {
                return Problem("Entity set 'casemanagementContext.Cmcustomers'  is null.");
            }
            var cmcustomer = await _context.Cmcustomers.FindAsync(id);
            if (cmcustomer != null)
            {
                _context.Cmcustomers.Remove(cmcustomer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CmcustomerExists(int id)
        {
          return _context.Cmcustomers.Any(e => e.Id == id);
        }
    }
}

Views/Cmcustomers/Create.cshtml
@model Case.Web.Portal.Models.Cmcustomer

@{
    ViewData["Title"] = "Create";
}

<p></p>

<div class="cta container">

<section id="customercare" class="team">
      <div class="container" data-aos="fade-up">


           <div class="section-header">
          <h2>Create Customer</h2>
          <p>View all customers here using the table below. </p>
        </div>
<div class=" contact">
    <div class="case-form col-lg-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedAt" class="control-label"></label>
                <input asp-for="UpdatedAt" class="form-control" />
                <span asp-validation-for="UpdatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                 <button type="submit" value="Create" class="" >Create</button>    
            </div>
        </form>
     </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>
</div>
</section>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cmcustomers/Delete.cshtml
@model Case.Web.Portal.Models.Cmcustomer

@{
    ViewData["Title"] = "Delete";
}

<p></p>

<div class="cta container">

<section id="customercare" class="team">
      <div class="container" data-aos="fade-up">


           <div class="section-header">
          <h2> Delete Customer</h2>
        </div>

<div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cmcase</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</div>
</div>
</section>
</div>

Views/Cmcustomers/Details.cshtml
@model Case.Web.Portal.Models.Cmcustomer

@{
    ViewData["Title"] = "Details";
}

<p></p>

<div class="cta container">

<section id="customercare" class="team">
      <div class="container" data-aos="fade-up">


           <div class="section-header">
          <h2>Case</h2>
        </div>

<div>
  
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</div>
</div>
</section>
</div>

Views/Cmcustomers/Edit.cshtml
@model Case.Web.Portal.Models.Cmcustomer

@{
    ViewData["Title"] = "Edit";
}

<p></p>

<div class="cta container">

<section id="customercare" class="team">
      <div class="container" data-aos="fade-up">


           <div class="section-header">
          <h2>Edit Customer</h2>
          <p>View all customers here using the table below. </p>
        </div>
<div class=" contact">
    <div class="case-form col-lg-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedAt" class="control-label"></label>
                <input asp-for="UpdatedAt" class="form-control" />
                <span asp-validation-for="UpdatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
 </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>
</div>
</section>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cmcustomers/Index.cshtml
@model IEnumerable<Case.Web.Portal.Models.Cmcustomer>

@{
    ViewData["Title"] = "Index";
}

<p>

</p>

<div class="cta container">

<section id="customers" class="team">
      <div class="container" data-aos="fade-up">


           <div class="section-header">
          <h2>All Customers</h2>
          <p>View all customers here using the table below. </p>
        </div>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row gy-5 pricing">
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.UpdatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
           @* <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                <a class="buy-btn" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="buy-btn" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="buy-btn" asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a class="buy-btn" href="~/UserCases?UserId=@item.Id" >Cases</a> |

                 <a class="buy-btn" href="@Url.Action("Create", "Cmcases", new { userId = item.Id })">
                 <span>Create Case</span>
                </a>
                 
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</section>
</div>